# Built-test-staging-prod pipeline

# Only run against master
trigger:
- master

# Don't run against PRs
pr: none

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: dotnet restore
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'


- stage: unit_tests
  dependsOn: build
  jobs:
  - job: run_tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      displayName: UnitTests
      inputs:
        command: test
        projects: '**/tests/**/*UnitTests.csproj'
        arguments: '--configuration $(buildConfiguration)'


- stage: copy_to_staging_directory
  dependsOn: unit_tests
  jobs:
  - job: copy_build_output
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: dotnet publish --output $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
  - job: copy_configuration_files
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CopyFiles@2
      displayName: 'Copy *settings.json to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: '**/*settings.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: CopyFiles@2
      displayName: 'Copy *runtimeconfig.json to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: '**/*runtimeconfig.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: FileTransform@1
      inputs:
        folderPath: '$(Build.ArtifactStagingDirectory)/**/*Tests*'
        fileType: json
        targetFiles: local.settings.json


- stage: intergration_tests
  dependsOn: copy_to_staging_directory
  jobs:  
  - job: variables_transformations
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: '**\*IntegrationTest*.dll
          !**\*TestAdapter.dll
          !**\*TestPlatform*.dll
          !**\*testhost*.dll
          !**\*UnitTest*.dll
          !**\obj\**'
        searchFolder: '$(Build.ArtifactStagingDirectory)'
        otherConsoleOptions: '/platform:x64 /Framework:.NETCoreApp,Version=v2.1 /logger:console;verbosity="normal"'
