# Built-test-staging-prod pipeline

# Only run against master
trigger:
- master

# Don't run against PRs
pr: none

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: dotnet restore
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

- stage: unit_tests
  dependsOn: build
  jobs:
  - job: run_tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      displayName: UnitTests
      inputs:
        command: test
        projects: '**/tests/**/*UnitTests.csproj'
        arguments: '--configuration $(buildConfiguration)'     


- stage: intergration_tests
  dependsOn: unit_tests
  jobs:  
  - job: variables_transformations
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: FileTransform@1
      inputs:
        folderPath: '$(Build.SourcesDirectory)/$(integrationTestsFolder)/'
        fileType: json
        targetFiles: local.settings.json
    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: '**\*IntegrationTest*.dll
          !**\*TestAdapter.dll
          !**\*TestPlatform*.dll
          !**\*testhost*.dll
          !**\*UnitTest*.dll
          !**\obj\**'
        searchFolder: '$(Build.SourcesDirectory)'
        otherConsoleOptions: '/platform:x64 /Framework:.NETCoreApp,Version=v2.1 /logger:console;verbosity="normal"'
