# https://stackoverflow.com/questions/54718866/azure-pipeline-nuget-package-versioning-scheme-how-to-get-1-0-revr
#Set build number automatically
name: $(majorMinorVersion).$(semanticVersion) # $(rev:r) # NOTE: rev resets when the default retention period expires

# pipeline variables
variables:
  majorMinorVersion: 1.0
  # semanticVersion counter is automatically incremented by one in each execution of pipeline
  # second parameter is seed value to reset to every time the referenced majorMinorVersion is changed
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]

# Only run against master
trigger:
- master

# Don't run against PRs
pr: none

stages:
- stage: build_and_unitTests
  jobs:
  - job: run_build_and_unitTests
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: dotnet restore
    
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    
    - task: DotNetCoreCLI@2
      displayName: UnitTests
      inputs:
        command: test
        projects: '**/tests/**/*UnitTests.csproj'
        arguments: '--configuration $(buildConfiguration)'      

- stage: integrationTests_and_nugetpush
  dependsOn: build_and_unitTests
  jobs:
  - job: publish
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: dotnet publish --output $(Build.ArtifactStagingDirectory)

    - task: FileTransform@1
      inputs:
        folderPath: '$(Build.ArtifactStagingDirectory)'
        fileType: json
        targetFiles: local.settings.json  
        
    - task: VSTest@2
      condition: eq(variables['RunIntegrationTests'], true)
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: '**\*.IntegrationTests.dll'
        searchFolder: '$(Build.ArtifactStagingDirectory)'
        otherConsoleOptions: '/platform:x64 /Framework:.NETCoreApp,Version=v2.1 /logger:console;verbosity="normal"'

    - task: NuGetCommand@2
      condition: eq(variables['PushPackage'], true)
      inputs:
        command: 'pack'
        packagesToPack: '**/Microsoft.Azure.Storage.Table.Repository.csproj'
        versioningScheme: byBuildNumber # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#yaml-snippet

    - task: NuGetCommand@2
      condition: eq(variables['PushPackage'], true)
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '02744400-58ba-47b7-9683-250b0ee8be39'

#    - task: PublishBuildArtifacts@1
