# Only run against master
trigger:
- master

# Don't run against PRs
pr: none

stages:
- stage: build_and_unitTests
  jobs:
  - job: run_build_and_unitTests
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: dotnet restore
    
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    
    - task: DotNetCoreCLI@2
      displayName: UnitTests
      inputs:
        command: test
        projects: '**/tests/**/*UnitTests.csproj'
        arguments: '--configuration $(buildConfiguration)'      

- stage: integrationTests_and_nugetpush
  dependsOn: build_and_unitTests
  jobs:
  - job: publish
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: dotnet publish --output $(Build.ArtifactStagingDirectory)

    - task: FileTransform@1
      inputs:
        folderPath: '$(Build.ArtifactStagingDirectory)'
        fileType: json
        targetFiles: local.settings.json  
        
    - task: VSTest@2
      condition: $(RunIntegrationTests)
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: '**\*.IntegrationTests.dll'
        searchFolder: '$(Build.ArtifactStagingDirectory)'
        otherConsoleOptions: '/platform:x64 /Framework:.NETCoreApp,Version=v2.1 /logger:console;verbosity="normal"'

    - task: NuGetCommand@2
      condition: $(PushPackage)
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'Nuget official' 

#    - task: PublishBuildArtifacts@1
