# Built-test-staging-prod pipeline

# Only run against master
trigger:
- master

# Don't run against PRs
pr: none

stages:
- stage: build_and_unitTests
  jobs:
  - job: run_build_and_unitTests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: dotnet restore
    
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    
    - task: DotNetCoreCLI@2
      displayName: UnitTests
      inputs:
        command: test
        projects: '**/tests/**/*UnitTests.csproj'
        arguments: '--configuration $(buildConfiguration)'
    
    - script: dotnet publish --output $(Build.ArtifactStagingDirectory)
    
    - task: PublishBuildArtifacts@1
    
    - task: CopyFiles@2
      displayName: 'Copy *settings.json to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: '**/*settings.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

- stage: copy_configuration_files_to_staging_directory
  dependsOn: build_and_unitTests
  jobs:
  - job: copy_configuration_files
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: none
    - task: CopyFiles@2
      displayName: 'Copy *settings.json to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: '**/*settings.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'    

    - task: FileTransform@1
      inputs:
        folderPath: '$(Build.ArtifactStagingDirectory)/**/*IntegrationTests*'
        fileType: json
        targetFiles: local.settings.json


- stage: intergration_tests
  dependsOn: copy_configuration_files_to_staging_directory
  jobs:  
  - job: variables_transformations
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: none    
    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: '**\*IntegrationTests*.dll
          !**\*TestAdapter.dll
          !**\*TestPlatform*.dll
          !**\*testhost*.dll
          !**\*UnitTest*.dll
          !**\obj\**'
        searchFolder: '$(Build.ArtifactStagingDirectory)'
        otherConsoleOptions: '/platform:x64 /Framework:.NETCoreApp,Version=v2.1 /logger:console;verbosity="normal"'
