# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: UnitTests
  inputs:
    command: test
    projects: '**/tests/**/*UnitTests.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy local.settings.json to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: |
     **\local.settings.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'


- script: dotnet publish --output $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1



