# Built-test-staging-prod pipeline

# Only run against master
trigger:
- master

# Don't run against PRs
pr: none

stages:
- stage: build_and_unitTests
  jobs:
  - job: run_build_and_unitTests
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: dotnet restore
    
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    
    - task: DotNetCoreCLI@2
      displayName: UnitTests
      inputs:
        command: test
        projects: '**/tests/**/*UnitTests.csproj'
        arguments: '--configuration $(buildConfiguration)'      

- stage: integrationTests
  dependsOn: build_and_unitTests
  jobs:
  - job: publish
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: dotnet publish --output $(Build.ArtifactStagingDirectory)

    - task: FileTransform@1
      inputs:
        folderPath: '$(Build.ArtifactStagingDirectory)'
        fileType: json
        targetFiles: local.settings.json  
        
    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: '**\Microsoft.Azure.Storage.Table.Repository.IntegrationTests.dll'
        searchFolder: '$(Build.ArtifactStagingDirectory)'
        otherConsoleOptions: '/platform:x64 /Framework:.NETCoreApp,Version=v2.1 /logger:console;verbosity="normal"'

    - task: PublishBuildArtifacts@1
